/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasBke;

import backEnd.Producto;
import datos.Validacion;
import javax.swing.JOptionPane;

/**
 * Clase que representa la ventana de agregar productos que podrá ser 
 * @author Javier
 */
public class Agregar extends javax.swing.JDialog {

    /**
     * Creates new form Agregar
     */
    
    public Agregar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen1 = new imagen.PanelImagen();
        nombre = new javax.swing.JTextField();
        azucares = new javax.swing.JTextField();
        grasSat = new javax.swing.JTextField();
        grasTot = new javax.swing.JTextField();
        sodio = new javax.swing.JTextField();
        categoria = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        sCal = new javax.swing.JCheckBox();
        sGras = new javax.swing.JCheckBox();
        sAzu = new javax.swing.JCheckBox();
        sSod = new javax.swing.JCheckBox();
        aceptar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        calorias = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nombre.setText("Nombre");
        nombre.setPreferredSize(new java.awt.Dimension(160, 30));
        nombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreMouseClicked(evt);
            }
        });

        azucares.setText("Azucares %");
        azucares.setPreferredSize(new java.awt.Dimension(160, 30));
        azucares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                azucaresMouseClicked(evt);
            }
        });

        grasSat.setText("Grasas Saturadas %");
        grasSat.setPreferredSize(new java.awt.Dimension(160, 30));
        grasSat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grasSatMouseClicked(evt);
            }
        });

        grasTot.setText("Grasas Totales %");
        grasTot.setPreferredSize(new java.awt.Dimension(160, 30));
        grasTot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grasTotMouseClicked(evt);
            }
        });

        sodio.setText("Sodio %");
        sodio.setPreferredSize(new java.awt.Dimension(160, 30));
        sodio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sodioMouseClicked(evt);
            }
        });

        categoria.setText("Categoria");
        categoria.setPreferredSize(new java.awt.Dimension(160, 30));
        categoria.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriaMouseClicked(evt);
            }
        });

        codigo.setText("Codigo");
        codigo.setPreferredSize(new java.awt.Dimension(160, 30));
        codigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                codigoMouseClicked(evt);
            }
        });

        jLabel1.setText("Sellos:");

        sCal.setBackground(new java.awt.Color(255, 255, 255));
        sCal.setText("Calorias");

        sGras.setBackground(new java.awt.Color(255, 255, 255));
        sGras.setText("Grasas totales");

        sAzu.setBackground(new java.awt.Color(255, 255, 255));
        sAzu.setText("Azucares");

        sSod.setBackground(new java.awt.Color(255, 255, 255));
        sSod.setText("Sodio");

        aceptar.setBackground(new java.awt.Color(255, 255, 255));
        aceptar.setText("Aceptar");
        aceptar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        cancelar.setBackground(new java.awt.Color(255, 255, 255));
        cancelar.setText("Cancelar");
        cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        calorias.setText("Calorias %");
        calorias.setPreferredSize(new java.awt.Dimension(160, 30));
        calorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                caloriasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                .addContainerGap(352, Short.MAX_VALUE)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(sGras, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sCal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sAzu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sSod, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(70, 70, 70)
                        .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(grasSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grasTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(azucares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(calorias, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagen1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calorias, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addComponent(azucares, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grasTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(grasSat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sCal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sGras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sAzu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sSod)))
                .addGap(18, 18, 18)
                .addComponent(sodio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreMouseClicked
        nombre.setText("");
    }//GEN-LAST:event_nombreMouseClicked

    private void azucaresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_azucaresMouseClicked
        azucares.setText("");
    }//GEN-LAST:event_azucaresMouseClicked

    private void grasTotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grasTotMouseClicked
        grasTot.setText("");
    }//GEN-LAST:event_grasTotMouseClicked

    private void grasSatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grasSatMouseClicked
        grasSat.setText("");
    }//GEN-LAST:event_grasSatMouseClicked

    private void sodioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sodioMouseClicked
        sodio.setText("");
    }//GEN-LAST:event_sodioMouseClicked

    private void categoriaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriaMouseClicked
        categoria.setText("");
    }//GEN-LAST:event_categoriaMouseClicked

    private void codigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_codigoMouseClicked
        codigo.setText("");
    }//GEN-LAST:event_codigoMouseClicked

    private void caloriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_caloriasMouseClicked
        calorias.setText("");
    }//GEN-LAST:event_caloriasMouseClicked

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        if (new Validacion(codigo.getText()).comas()||new Validacion(categoria.getText()).comas()||new Validacion(nombre.getText()).comas()||
                new Validacion(calorias.getText()).comas()||new Validacion(azucares.getText()).comas()||
                new Validacion(grasTot.getText()).comas()||new Validacion(grasSat.getText()).comas()||new Validacion(sodio.getText()).comas()) {
            JOptionPane.showMessageDialog(null, "Por favor elimine las comas que hay en los campos.");
        }else
        {
            Producto producto = new Producto();
            producto.agregarProducto(new Producto(codigo.getText(),categoria.getText().toLowerCase(),nombre.getText().toLowerCase(),setSelloCalorias(),setSelloGrasas(),
                setSelloAzucares(),setSelloSodio(),calorias.getText(),azucares.getText(),grasTot.getText(),grasSat.getText(),sodio.getText()));
            JOptionPane.showMessageDialog(null, "El producto fue agregado con éxito, por favor refresque la lista para poder verlo.");
            this.dispose();
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed
    //Compara sCal para poder escribir si tiene sellos o no.
    private String setSelloCalorias(){
        String sello="Sin sellos";
        if (sCal.isSelected()) {
            sello="Alto en Calorias";
        }
        return sello;
    }
    //Compara sCal para poder escribir si tiene sellos o no.
    private String setSelloGrasas(){
        String sello="Sin sellos";
        if (sGras.isSelected()) {
            sello="Alto en Grasas";
        }
        return sello;
    }
    //Compara sCal para poder escribir si tiene sellos o no.
    private String setSelloAzucares(){
        String sello="Sin sellos";
        if (sAzu.isSelected()) {
            sello="Alto en Azucares";
        }
        return sello;
    }
    //Compara sCal para poder escribir si tiene sellos o no.
    private String setSelloSodio(){
        String sello="Sin sellos";
        if (sSod.isSelected()) {
            sello="Alto en Sodio";
        }
        return sello;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Agregar dialog = new Agregar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JTextField azucares;
    private javax.swing.JTextField calorias;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField categoria;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField grasSat;
    private javax.swing.JTextField grasTot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombre;
    private imagen.PanelImagen panelImagen1;
    private javax.swing.JCheckBox sAzu;
    private javax.swing.JCheckBox sCal;
    private javax.swing.JCheckBox sGras;
    private javax.swing.JCheckBox sSod;
    private javax.swing.JTextField sodio;
    // End of variables declaration//GEN-END:variables
}
