/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasFte;

import backEnd.Producto;

/**
 *
 * @author Javier
 */
public class BusquedaPro extends javax.swing.JFrame {

    /**
     * Creates new form BusquedaPro
     */
    Producto producto = new Producto();
    public BusquedaPro() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
    }
    public void setNombre(String dato){
        nombre.setText(dato);
    }
    public void setCategoria(String dato){
        categoriaR.setText(dato);
    }

    public void setSelloCalorias(String dato){
        selloCalR.setText(dato);
    }
    public void setSelloGrasas(String dato){
        selloGrasR.setText(dato);
    }
    public void setSelloAzucares(String dato){
        selloAzuR.setText(dato);
    }
    public void setSelloSodio(String dato){
        selloSodR.setText(dato);
    }
    public void setAzucares(String dato){
        azucaresR.setText(dato);
    }
    public void setGrasasTot(String dato){
        grasasTotR.setText(dato);
    }
    public void setGrasasSat(String dato){
        grasasSatR.setText(dato);
    }
    public void setSodio(String dato){
        sodioR.setText(dato);
    }
    public void setCalorias(String dato){
        caloriasR.setText(dato);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelImagen1 = new imagen.PanelImagen();
        lCategoria = new javax.swing.JLabel();
        lSelloCal = new javax.swing.JLabel();
        lSelloGras = new javax.swing.JLabel();
        lSelloAzu = new javax.swing.JLabel();
        lSelloSodio = new javax.swing.JLabel();
        lCalorias = new javax.swing.JLabel();
        lAzucares = new javax.swing.JLabel();
        lGrasasTot = new javax.swing.JLabel();
        lGrasasSat = new javax.swing.JLabel();
        lSodio = new javax.swing.JLabel();
        sodioR = new javax.swing.JLabel();
        grasasSatR = new javax.swing.JLabel();
        grasasTotR = new javax.swing.JLabel();
        azucaresR = new javax.swing.JLabel();
        caloriasR = new javax.swing.JLabel();
        selloSodR = new javax.swing.JLabel();
        selloAzuR = new javax.swing.JLabel();
        selloGrasR = new javax.swing.JLabel();
        selloCalR = new javax.swing.JLabel();
        categoriaR = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagen1.setPreferredSize(new java.awt.Dimension(1000, 600));

        lCategoria.setText("Categoria:");

        lSelloCal.setText("Sello Calorías :");

        lSelloGras.setText("Sello Grasas :");

        lSelloAzu.setText("Sello Azúcares :");

        lSelloSodio.setText("Sello Sodio :");

        lCalorias.setText("Calorías :");

        lAzucares.setText("Azúcares :");

        lGrasasTot.setText("Grasas Totales :");

        lGrasasSat.setText("Grasas Saturadas:");

        lSodio.setText("Sodio :");

        sodioR.setText("Sodio");

        grasasSatR.setText("Grasas Saturadas");

        grasasTotR.setText("Grasas Totales");

        azucaresR.setText("Azucares");

        caloriasR.setText("Calorias");

        selloSodR.setText("Sello Sodio");

        selloAzuR.setText("selloAzucares");

        selloGrasR.setText("Sello Grasas");

        selloCalR.setText("Sello Calorias");

        categoriaR.setText("Categoria");

        nombre.setText("Nombre");

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setText("volver");
        volver.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                .addContainerGap(564, Short.MAX_VALUE)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                        .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lGrasasSat)
                                .addComponent(lSelloSodio, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lCalorias, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lGrasasTot, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lAzucares, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lSodio, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lCategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lSelloCal, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lSelloGras, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lSelloAzu, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(112, 112, 112)
                        .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categoriaR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selloCalR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selloGrasR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selloAzuR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(selloSodR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(caloriasR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(azucaresR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(grasasTotR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(grasasSatR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sodioR, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                        .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                        .addComponent(volver)
                        .addContainerGap())))
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagen1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver)
                .addGap(93, 93, 93)
                .addComponent(nombre)
                .addGap(48, 48, 48)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addComponent(lCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSelloCal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSelloGras)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSelloAzu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSelloSodio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lCalorias)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lAzucares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lGrasasTot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lGrasasSat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lSodio))
                    .addGroup(panelImagen1Layout.createSequentialGroup()
                        .addComponent(categoriaR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selloCalR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selloGrasR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selloAzuR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selloSodR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caloriasR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(azucaresR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grasasTotR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(grasasSatR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sodioR)))
                .addContainerGap(178, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelImagen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new DitagVP().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BusquedaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BusquedaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BusquedaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BusquedaPro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BusquedaPro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel azucaresR;
    private javax.swing.JLabel caloriasR;
    private javax.swing.JLabel categoriaR;
    private javax.swing.JLabel grasasSatR;
    private javax.swing.JLabel grasasTotR;
    private javax.swing.JLabel lAzucares;
    private javax.swing.JLabel lCalorias;
    private javax.swing.JLabel lCategoria;
    private javax.swing.JLabel lGrasasSat;
    private javax.swing.JLabel lGrasasTot;
    private javax.swing.JLabel lSelloAzu;
    private javax.swing.JLabel lSelloCal;
    private javax.swing.JLabel lSelloGras;
    private javax.swing.JLabel lSelloSodio;
    private javax.swing.JLabel lSodio;
    private javax.swing.JLabel nombre;
    private imagen.PanelImagen panelImagen1;
    private javax.swing.JLabel selloAzuR;
    private javax.swing.JLabel selloCalR;
    private javax.swing.JLabel selloGrasR;
    private javax.swing.JLabel selloSodR;
    private javax.swing.JLabel sodioR;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
