/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanasFte;

import VentanasBke.Login;
import backEnd.Producto;
import datos.Validacion;
import javax.swing.JOptionPane;

/**
 *
 * @author Javier
 */
public class DitagVP extends javax.swing.JFrame {

    /**
     * Creates new form DitagVP
     */
    Producto producto = new Producto();
    public DitagVP() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(this);
        rbBuscarP.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoBusqueda = new javax.swing.ButtonGroup();
        panelImagen1 = new imagen.PanelImagen();
        jButton1 = new javax.swing.JButton();
        txtbusqueda = new javax.swing.JTextField();
        bBuscar = new javax.swing.JButton();
        rbBuscarP = new javax.swing.JRadioButton();
        rbBuscarCat = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelImagen1.setPreferredSize(new java.awt.Dimension(1000, 600));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Administrador");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtbusqueda.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtbusqueda.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtbusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbusquedaActionPerformed(evt);
            }
        });
        txtbusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbusquedaKeyTyped(evt);
            }
        });

        bBuscar.setBackground(new java.awt.Color(255, 255, 255));
        bBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bBuscar.setText("Buscar");
        bBuscar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        bBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarActionPerformed(evt);
            }
        });

        rbBuscarP.setBackground(new java.awt.Color(255, 255, 255));
        tipoBusqueda.add(rbBuscarP);
        rbBuscarP.setText("Buscar Producto");

        rbBuscarCat.setBackground(new java.awt.Color(255, 255, 255));
        tipoBusqueda.add(rbBuscarCat);
        rbBuscarCat.setText("Buscar Categoria");

        javax.swing.GroupLayout panelImagen1Layout = new javax.swing.GroupLayout(panelImagen1);
        panelImagen1.setLayout(panelImagen1Layout);
        panelImagen1Layout.setHorizontalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagen1Layout.createSequentialGroup()
                .addContainerGap(308, Short.MAX_VALUE)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                        .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelImagen1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap())))
            .addGroup(panelImagen1Layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(rbBuscarP)
                .addGap(38, 38, 38)
                .addComponent(rbBuscarCat)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelImagen1Layout.setVerticalGroup(
            panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelImagen1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(254, 254, 254)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbBuscarP)
                    .addComponent(rbBuscarCat))
                .addContainerGap(239, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelImagen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Login login = new Login(this, true);
        login.setDefaultCloseOperation(0);
        login.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarActionPerformed
        if (rbBuscarP.isSelected()) {
            try {
                BusquedaPro busqueda = new BusquedaPro();
                busqueda.setNombre(txtbusqueda.getText());
                busqueda.setCategoria(producto.buscarProducto(txtbusqueda.getText()).getCategoria());
                busqueda.setSelloCalorias(producto.buscarProducto(txtbusqueda.getText()).getSelloCaloria());
                busqueda.setSelloGrasas(producto.buscarProducto(txtbusqueda.getText()).getSelloGrasas());
                busqueda.setSelloAzucares(producto.buscarProducto(txtbusqueda.getText()).getSelloAzucares());
                busqueda.setSelloSodio(producto.buscarProducto(txtbusqueda.getText()).getSelloSodio());
                busqueda.setCalorias(producto.buscarProducto(txtbusqueda.getText()).getCalorias());
                busqueda.setAzucares(producto.buscarProducto(txtbusqueda.getText()).getAzucares());
                busqueda.setGrasasTot(producto.buscarProducto(txtbusqueda.getText()).getGrasasTot());
                busqueda.setGrasasSat(producto.buscarProducto(txtbusqueda.getText()).getGrasasSat());
                busqueda.setSodio(producto.buscarProducto(txtbusqueda.getText()).getSodio());
                busqueda.setVisible(true);
                this.dispose();
            } catch (Exception e) {
            }
           
        }else
        {
            if("".equals(txtbusqueda.getText())){
                JOptionPane.showMessageDialog(null, "Ingrese una categoria porfavor");
            }else
            {
                BusquedaCat busqueda = new BusquedaCat();
                busqueda.setCategoria(txtbusqueda.getText());
                busqueda.setModelo(txtbusqueda.getText());
                busqueda.setVisible(true);
                this.dispose();
            }
        } 
    }//GEN-LAST:event_bBuscarActionPerformed

    private void txtbusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbusquedaActionPerformed

    private void txtbusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbusquedaKeyTyped
        
    }//GEN-LAST:event_txtbusquedaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DitagVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DitagVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DitagVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DitagVP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DitagVP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton jButton1;
    private imagen.PanelImagen panelImagen1;
    private javax.swing.JRadioButton rbBuscarCat;
    private javax.swing.JRadioButton rbBuscarP;
    private javax.swing.ButtonGroup tipoBusqueda;
    private javax.swing.JTextField txtbusqueda;
    // End of variables declaration//GEN-END:variables
}
